---
# ------------------------------------------------------------------------
# handlers file for ntp
# ------------------------------------------------------------------------

- name: restart ntp
  service:
    name: "{{ ntp_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
